name: DeathNotePlugin
version: '${version}'
main: com.github.mckumama3.deathnoteplugin.deathnoteplugin.DeathNotePlugin
api-version: 1.17

commands:
  start:
    description: start Game
  end:
    description: end Game
